version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/django
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
